### ISSUE TITLE
[PathBundle] Copie d'un parcours et publication

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1283]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

La copie d'un parcours publié engendre un parcours non publié

Il faudrait que la copie soit publié

Pour une simple copie, ce n'est pas trop gênant mais quand on crée une session de formation via la gestion des formations, dotés de nombreux parcours, c'est gênant ( il faut revoir et publier tous les parcours pour toutes les sessions)

**Comment by CPASimUSante** [comment]
IMO, this doesn't seem a good idea because in a regular case, if you copy a Path, you want to use it as a "template" : you will make adjustments here and there and don't want the users to be able to use it before you tested it all.
If you want an exact copy (a clone), why don't you use a Shortcut resource ?

**Comment by jj-quintin** [comment]
Je comprends pour une simple copie 

Mais ce n'est pas ce qu'on cherche quand on utilise les modèles dans la gestion des cursus

L'idée des cursus (appelé maintenant gestion des formations) c'est de développer un modèle sur la base d'un WS, puis de récupérer le modèle dans la gestion des formations et de créer une série de "sessions" se basant sur ce modèle

Toutes les ressources se basant sur ce système de sessions/modèle sont bien publiées, à l'exception des parcours

C'est pas bien grave... sauf pour celui qui a bcp de parcours et bcp de sessions

**Comment by Elorfin** [comment]
fixed
