### ISSUE TITLE
[ExoBundle] Think about a new paper management

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1789]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

In a future, we should think of an other way of managing the papers. 
At the moment all the papers  are saved : one paper by attempt for every user. It could be quickly unmanageable to keep all of them. Maybe use versioning ? Be able to delete some papers ?

**Comment by stefk** [comment]
One big issue here is that every paper stores the whole quiz data. On systems with a lot of users and rather large quizzes (e.g. using embedded media), it could lead to storage size problems. Storing each version of a quiz/question only once and referencing these versions in the papers instead of inlining them could be a solution.
