### ISSUE TITLE
Log In button

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#188]
Add the possibility to specify the behavior of the Log In button :
- redirect to Desktop (like now)
- don't redirect and stay on the same active page
- redirect to a page/URL
in an Administration option or in parameters files

**Comment by eddymarques** [comment]
J'ai mis Panos sur la fonctionnalité. Je suis en train de rédiger une explication pour la liste de diffusion

**Comment by ptsavdar** [comment]
@LaurentGruber @ngodfraind I'm about to finish implementing this enhancement and I would like to share some of my concerns with you. First of all, I'd like to inform you that I've replaced the "Redirect to last visited page" check button with this radios:
![redirect_after_login](https://cloud.githubusercontent.com/assets/3414935/14950285/d707047a-1050-11e6-8660-26d9d21ced7b.jpg)

My first concern is that when the admin checked the "Redirect to last visited page" option, the page uri was saved to the user table every time a user visited a page. Is this behavior really necessary? Because if not I think that we ca avoid having an extra sql query for no necessary reason. Apparently if we want to save the last visited page for the user to be able to start his new session right where he left off, using the same or another terminal, we need to keep it active. But if we don't, I think we can remove it.

Secondly, there's the option to choose a workspace tag to load on login which cancels the "Redirect after login" option and might confuse admins. I think that using the url option, it also covers the possibility to load a workspace after login by targeting this workspace using its URL.

What do you think?

**Comment by ngodfraind** [comment]
If you can get the last active page without the database, I agree it's way better.

@kitan1982 How do workspace tags work ?

**Comment by kitan1982** [comment]
The workspace tag option allow to redirect the user to a tagged workspace he is registered in.
The tagged workspace can be different from one user to another.
A fixed URL will not be sufficient to fullly replace this option.

**Comment by ptsavdar** [comment]
@kitan1982 Ok, I'll add it as a forth option under the "redirect after login". That way one action will not cancel the other and it will be more consistent.
@kitan1982 @ngodfraind Thank you both for your prompt reply.

**Comment by ptsavdar** [comment]
Ok fixed
