### ISSUE TITLE
[ExoBundle] make drag and drop possible on tablet

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2137]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Drag and drop is needed to reorganize steps and questions in the editor and to be able to create and respond to set, association and pair questions.

**Comment by Elorfin** [comment]
https://github.com/yahoo/react-dnd-touch-backend

**Comment by pitrackster** [comment]
@Elorfin unfortunately not simple as swaping from one backend to another one. The touch backend seems to have problems with mouse events while html5 backend does not handle touch events at all...

From the doc

Mouse events support*

You can enable capturing mouse events by configuring your TouchBackend as follows:

DragDropContext(TouchBackend({ enableMouseEvents: true }));
NOTE*: This is buggy due to the difference in touchstart/touchend event propagation compared to mousedown/mouseup/click. I highly recommend that you use react-dnd-html5-backend instead for a more performant native HTML5 drag capability.

**Comment by Elorfin** [comment]
Yes, it's not that simple. 
I've put it here for reference. There may be a way to detect the execution context and switch from one backend to another. For example, we can test for the existence of `touchstart` event or something like this.

**Comment by Elorfin** [comment]
It seems touch detection is not perfect : http://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript/4819886#4819886.

But it can be better than nothing if we can not find a DND backend that can handle both touch and mouse.

**Comment by pitrackster** [comment]
Maybe this lib could help http://hammerjs.github.io/

**Comment by om64** [comment]
This is urgent, anyway. I'm working with a test class in about three weeks and all the pupils use iPads.
