### ISSUE TITLE
Conflict between datepicker styles

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#356]
The styles of `bootstrap-datepicker` completly break those used by `angular-strap` datepicker.

**NB 1** : `bootstrap-datepicker` styles are included in all the pages (through `ClarolineCoreBundle:Layout:stylesheets.html.twig`).

**NB 2** : the datepicker provided by `angular-strap` is actually the only angular datepicker we have included in the dependency (as the one of `angular-bootstrap` uses glyphicon in a non configurable way).

The workaround is to had this line in your styles : 

```
.dropdown-menu.datepicker {
    width: 250px;

    table tr td,
    table tr th {
        border-radius: 0;
        width: auto;
        height: auto;
    }

    button {
        outline: none;
        border: 0px;
    }

    tbody button {
        padding: 6px;
    }

    span {
        border-radius: 0;
        width: auto;
        height: auto;
        line-height: @line-height-base;
        float: none;
        margin: 0;
    }
}
```

**Comment by CPASimUSante** [comment]
i'm trying to "angularize" a bundle and i have problems related to this : 
The glyphicons are not working.
![datepicker](https://cloud.githubusercontent.com/assets/14015697/15476056/67f013a6-210d-11e6-805b-f01e0a99cbd8.png)
I also have trouble managing picker interface translation.

In my bundle i only use  'bootstrap-datepicker' in angular (angular-strap seems a very recent dependency, since it wasn't in bower.json last time i checked.)

**Comment by CPASimUSante** [comment]
So do you mean, since angular-strap is a dependency, that the css you give as a fix should be added to the main css for every usercase, in a PR ?
