### ISSUE TITLE
"third party" login

### ISSUE THREAD

**Issue by arnaudbey** [claroline/Distribution#662]
Hey there,

I would like to know in what extent it would be possible to use the login system of a Claroline instance to log in another symfony3 application, which would also have its proper login system
Any ideas / hints ? 

Thanks :rabbit:

**Comment by stefk** [comment]
AFAIK Claroline instances can act like OAuth providers, so that's probably a way to do it. You'd have to set up an OAuth lib/bundle in your app and offer an alternate authentication method, which would send a client id/secret previously registered on the Claroline side. The details should then be handled by the underlying Oauth lib.

I haven't done this before so you might want the input of @ngodfraind on the subject.

**Comment by arnaudbey** [comment]
Thanks !

@ngodfraind Is there any recommended lib, or an already used one ? 
Could that system can handle SSO or it's a completly different problematic ?

**Comment by ptsavdar** [comment]
AFAIK, there is the https://github.com/hwi/HWIOAuthBundle that you can check. We're using it on the https://github.com/iCAPLyon1/OAuthBundle to connect using third party APIs such as Facebook, LinkedIn, Twitter etc. I don't know if this is much of a help, though I hope it would be.

**Comment by arnaudbey** [comment]
I'll have a look, thanks 👍
