### ISSUE TITLE
[Outils du bureau] renommage du nom des outils

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#713]
La fonctionnalité "Outils du bureau" qui devait permettre le renommage des noms des outils dans la plateforme, a disparu du menu d'administration.
Est-il prévu de la rendre de nouveau disponible?

![image](https://cloud.githubusercontent.com/assets/3414956/16271648/21417544-389b-11e6-8463-5ddf78c040a4.png)

**Comment by LaurentGruber** [comment]
A priori non, on l'a supprimé parce qu'il ne fonctionnait pas vraiment et qu'on ne voyait pas à quoi il devait servir vu que le nom des outils se modifient directement dans les espaces d'acivités. Tu le voudrais pour quoi ?

**Comment by ngodfraind** [comment]
En fait, avec les icônes, la seule chose que cet outil pouvait faire était
de renommer la balise title (et il ne le faisait pas partout). C'est léger
quand même.

Le 23 juin 2016 à 09:41, Gruber Laurent <notifications@github.com> a écrit :

> A priori non, on l'a supprimé parce qu'il ne fonctionnait pas vraiment et
> qu'on ne voyait pas à quoi il devait servir vu que le nom des outils se
> modifient directement dans les espaces d'acivités. Tu le voudrais pour quoi
> ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/claroline/Distribution/issues/713#issuecomment-227973853>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABVStuvXqu14sP9dVk16IcVbGKcU1e29ks5qOjitgaJpZM4I74b3>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by eddymarques** [comment]
J'ai eu cette demande à plusieurs reprises.
Les gestionnaires des plateformes concernées voulaient adapter les noms des outils par rapport à leur contexte.
"Espace d'activité" est le plus souvent ciblé, car c'est un terme qui n'est pas parlant du tout dans leur environnement. Pouvoir le renommer en "Cours", "Module" etc...
Ça touche d'autres outils évidemment, comme "Ressources" en "Documents consultables" et bien d'autres encore.

En effet les outils peuvent être renommés dans chaque espace d'activité. Mais ça ne permet pas de garder une unité sur toute la plateforme. Les créateurs d'espace non avertis pourront se retrouver avec des outils similaires mais qui n'ont pas le même nom. Ça peut être déroutant.
Est-ce que les termes sont conservés si on utilise les modèles?

**Comment by LaurentGruber** [comment]
Pour espace d'activité j'ai déjà eu la demande également. On pourrait lister les termes qu'on souhaiterait pouvoir adapter et faire quelque chose mais cela pause pour moi 2 problèmes : 

1. La communication (manuel, tuto,...) pour le support si quelqu'un renome EA en cours et que partout on parle de EA, les utilisateurs vont avoir du mal à s'y retrouver
2. Les performances, si à chaque chargement de page, on fait des requêtes en DB pour toute une série de terme, ce n'est pas top

@om64 @clarophil @jj-quintin vous avez un avis ?

**Comment by jj-quintin** [comment]
La solution imaginées (et à discuter) est ici : http://www.crea-tice.org/mediawiki/index.php?title=Traduction

Elle envisage cette question au niveau de l'instance (possibilité, offerte donc à un administrateur, plutôt péda, d'adapter certains termes pour l'ensemble de l'instance)

**Comment by jj-quintin** [comment]
@LaurentGruber 

Pour les deux problèmes que tu évoques : 

1. Effectivement, mais c'est la responsabilité de l'institution qui déciderait d'adapter certains termes qui, du coup, serait différents de ceux mentionnés dans les manuels en ligne. A eux d'adapter leurs manuels pour leur public. On garderait donc notre voc. CC
2. Pourquoi serait-ce différent d'une traduction classique (anglais, espagnol...) On aurait simplement de nouvelle variantes d'une langue de référence, considérées techniquement comme des "langues" (je parle au niveau technique)

**Comment by jj-quintin** [comment]
> La fonctionnalité "Outils du bureau" qui devait permettre le renommage des noms des outils dans la plateforme, a disparu du menu d'administration.
Est-il prévu de la rendre de nouveau disponible?

De notre côté c'est utilisé pour l'adaptation du nom de certains des outils à notre contexte de formation. On est donc assez partisan de garder cette possibilité, voire de l'étendre comme on le disait

**Comment by clarophil** [comment]
Je pense qu'il est nécessaire de pouvoir adapter le vocabulaire, nous sommes demandeurs de remplacer collaborateur par membre ou widget par bloc.  
Une solution pourrait être une surcharge du fichier de traduction car sinon on doit réadapter le fichier à chaque upgrade.

**Comment by eddymarques** [comment]
La solution du fichier de traduction me convient.
Cela implique cependant de créer une interface permettant de gérer les langues, et d'uploader un dictionnaire.

**Comment by LaurentGruber** [comment]
ok pour la gestion des traductions, on voit pour faire évoluer l'outil de gestion des traductions afin de permettre d'éditer des traductions local sans que ça pause de souci au niveau des mises à jour ...

**Comment by om64** [comment]
On voit ça ensemble dès qu’on a un moment.

 

Olivier Meinguet

Secrétaire général

 

AISBL Consortium Claroline

 



 

6, chemin du cyclotron

1348 Louvain-la-Neuve

Tél.: 0477 90 16 69

 <http://www.claroline.net/> www.claroline.net



 <http://www.facebook.com/consortiumclaroline>   <https://plus.google.com/u/0/112736720926447938003/posts>   <http://www.linkedin.com/groups?gid=23022&trk=myg_ugrp_ovr>   <https://www.youtube.com/channel/UCBHvKl_J25_lsPveETBfHtQ/playlists>   <https://github.com/claroline/Claroline>   <http://www.twitter.com/LMSClaroline> 

 

De : Gruber Laurent [mailto:notifications@github.com] 
Envoyé : mardi 28 juin 2016 16:20
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : ClarOli <olivier.meinguet@claroline.net>; Mention <mention@noreply.github.com>
Objet : Re: [claroline/Distribution] [Outils du bureau] renommage du nom des outils (#713)

 

ok pour la gestion des traductions, on voit pour faire évoluer l'outil de gestion des traductions afin de permettre d'éditer des traductions local sans que ça pause de souci au niveau des mises à jour ...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/claroline/Distribution/issues/713#issuecomment-229063476> , or mute the thread <https://github.com/notifications/unsubscribe/ANpV2hPyp7Zbagx8wf4pHDJgOx_LcrWBks5qQS1-gaJpZM4I74b3> .  <https://github.com/notifications/beacon/ANpV2leXN-0CaAc0A5k_APBy5pQh62-aks5qQS1-gaJpZM4I74b3.gif> 

Aucun virus trouvé dans ce message.
Analyse effectuée par AVG - www.avg.com <http://www.avg.com> 
Version: 2016.0.7640 / Base de données virale: 4613/12502 - Date: 27/06/2016
